// ══════════════════════════════════════════════════════════
// US STOCK DATABASE — Popular stocks for search & sector analysis
// Sectors: Tech, Healthcare, Financial, Energy, Consumer, Industrials,
//          Utilities, Real Estate, Communication, Materials, ETF
// ══════════════════════════════════════════════════════════
const STOCKS_DB=[
// ── Technology ────────────────────────────────
{t:'AAPL',n:'Apple Inc.',s:'Technology'},
{t:'MSFT',n:'Microsoft Corp.',s:'Technology'},
{t:'NVDA',n:'NVIDIA Corp.',s:'Technology'},
{t:'AMD',n:'Advanced Micro Devices',s:'Technology'},
{t:'INTC',n:'Intel Corp.',s:'Technology'},
{t:'TSM',n:'Taiwan Semiconductor',s:'Technology'},
{t:'AVGO',n:'Broadcom Inc.',s:'Technology'},
{t:'QCOM',n:'Qualcomm Inc.',s:'Technology'},
{t:'TXN',n:'Texas Instruments',s:'Technology'},
{t:'AMAT',n:'Applied Materials',s:'Technology'},
{t:'LRCX',n:'Lam Research',s:'Technology'},
{t:'KLAC',n:'KLA Corp.',s:'Technology'},
{t:'MU',n:'Micron Technology',s:'Technology'},
{t:'MRVL',n:'Marvell Technology',s:'Technology'},
{t:'ON',n:'ON Semiconductor',s:'Technology'},
{t:'CRM',n:'Salesforce Inc.',s:'Technology'},
{t:'ADBE',n:'Adobe Inc.',s:'Technology'},
{t:'ORCL',n:'Oracle Corp.',s:'Technology'},
{t:'NOW',n:'ServiceNow Inc.',s:'Technology'},
{t:'INTU',n:'Intuit Inc.',s:'Technology'},
{t:'SNOW',n:'Snowflake Inc.',s:'Technology'},
{t:'PLTR',n:'Palantir Technologies',s:'Technology'},
{t:'PANW',n:'Palo Alto Networks',s:'Technology'},
{t:'CRWD',n:'CrowdStrike Holdings',s:'Technology'},
{t:'FTNT',n:'Fortinet Inc.',s:'Technology'},
{t:'SHOP',n:'Shopify Inc.',s:'Technology'},
{t:'DDOG',n:'Datadog Inc.',s:'Technology'},
{t:'NET',n:'Cloudflare Inc.',s:'Technology'},
{t:'ZS',n:'Zscaler Inc.',s:'Technology'},
{t:'DELL',n:'Dell Technologies',s:'Technology'},
{t:'HPQ',n:'HP Inc.',s:'Technology'},
{t:'IBM',n:'IBM Corp.',s:'Technology'},
{t:'CSCO',n:'Cisco Systems',s:'Technology'},
{t:'ACN',n:'Accenture plc',s:'Technology'},
// ── Communication ─────────────────────────────
{t:'GOOGL',n:'Alphabet (Google)',s:'Communication'},
{t:'GOOG',n:'Alphabet Class C',s:'Communication'},
{t:'META',n:'Meta Platforms',s:'Communication'},
{t:'NFLX',n:'Netflix Inc.',s:'Communication'},
{t:'DIS',n:'Walt Disney Co.',s:'Communication'},
{t:'CMCSA',n:'Comcast Corp.',s:'Communication'},
{t:'T',n:'AT&T Inc.',s:'Communication'},
{t:'VZ',n:'Verizon Communications',s:'Communication'},
{t:'TMUS',n:'T-Mobile US',s:'Communication'},
{t:'SNAP',n:'Snap Inc.',s:'Communication'},
{t:'PINS',n:'Pinterest Inc.',s:'Communication'},
{t:'ROKU',n:'Roku Inc.',s:'Communication'},
{t:'SPOT',n:'Spotify Technology',s:'Communication'},
{t:'RBLX',n:'Roblox Corp.',s:'Communication'},
// ── Consumer Discretionary ────────────────────
{t:'AMZN',n:'Amazon.com Inc.',s:'Consumer'},
{t:'TSLA',n:'Tesla Inc.',s:'Consumer'},
{t:'HD',n:'Home Depot Inc.',s:'Consumer'},
{t:'LOW',n:'Lowe\'s Companies',s:'Consumer'},
{t:'NKE',n:'Nike Inc.',s:'Consumer'},
{t:'SBUX',n:'Starbucks Corp.',s:'Consumer'},
{t:'MCD',n:'McDonald\'s Corp.',s:'Consumer'},
{t:'TGT',n:'Target Corp.',s:'Consumer'},
{t:'TJX',n:'TJX Companies',s:'Consumer'},
{t:'ROST',n:'Ross Stores',s:'Consumer'},
{t:'BKNG',n:'Booking Holdings',s:'Consumer'},
{t:'ABNB',n:'Airbnb Inc.',s:'Consumer'},
{t:'UBER',n:'Uber Technologies',s:'Consumer'},
{t:'LYFT',n:'Lyft Inc.',s:'Consumer'},
{t:'F',n:'Ford Motor Co.',s:'Consumer'},
{t:'GM',n:'General Motors',s:'Consumer'},
{t:'RIVN',n:'Rivian Automotive',s:'Consumer'},
{t:'LULU',n:'Lululemon Athletica',s:'Consumer'},
// ── Consumer Staples ──────────────────────────
{t:'WMT',n:'Walmart Inc.',s:'Consumer Staples'},
{t:'COST',n:'Costco Wholesale',s:'Consumer Staples'},
{t:'KO',n:'Coca-Cola Co.',s:'Consumer Staples'},
{t:'PEP',n:'PepsiCo Inc.',s:'Consumer Staples'},
{t:'PG',n:'Procter & Gamble',s:'Consumer Staples'},
{t:'CL',n:'Colgate-Palmolive',s:'Consumer Staples'},
{t:'MDLZ',n:'Mondelez International',s:'Consumer Staples'},
{t:'KHC',n:'Kraft Heinz Co.',s:'Consumer Staples'},
{t:'GIS',n:'General Mills',s:'Consumer Staples'},
{t:'HSY',n:'Hershey Co.',s:'Consumer Staples'},
{t:'MO',n:'Altria Group',s:'Consumer Staples'},
{t:'PM',n:'Philip Morris International',s:'Consumer Staples'},
// ── Healthcare ────────────────────────────────
{t:'UNH',n:'UnitedHealth Group',s:'Healthcare'},
{t:'JNJ',n:'Johnson & Johnson',s:'Healthcare'},
{t:'LLY',n:'Eli Lilly & Co.',s:'Healthcare'},
{t:'PFE',n:'Pfizer Inc.',s:'Healthcare'},
{t:'ABBV',n:'AbbVie Inc.',s:'Healthcare'},
{t:'MRK',n:'Merck & Co.',s:'Healthcare'},
{t:'TMO',n:'Thermo Fisher Scientific',s:'Healthcare'},
{t:'ABT',n:'Abbott Laboratories',s:'Healthcare'},
{t:'DHR',n:'Danaher Corp.',s:'Healthcare'},
{t:'BMY',n:'Bristol-Myers Squibb',s:'Healthcare'},
{t:'AMGN',n:'Amgen Inc.',s:'Healthcare'},
{t:'GILD',n:'Gilead Sciences',s:'Healthcare'},
{t:'ISRG',n:'Intuitive Surgical',s:'Healthcare'},
{t:'MRNA',n:'Moderna Inc.',s:'Healthcare'},
{t:'CVS',n:'CVS Health Corp.',s:'Healthcare'},
// ── Financial ─────────────────────────────────
{t:'JPM',n:'JPMorgan Chase',s:'Financial'},
{t:'V',n:'Visa Inc.',s:'Financial'},
{t:'MA',n:'Mastercard Inc.',s:'Financial'},
{t:'BAC',n:'Bank of America',s:'Financial'},
{t:'WFC',n:'Wells Fargo & Co.',s:'Financial'},
{t:'GS',n:'Goldman Sachs',s:'Financial'},
{t:'MS',n:'Morgan Stanley',s:'Financial'},
{t:'BLK',n:'BlackRock Inc.',s:'Financial'},
{t:'SCHW',n:'Charles Schwab',s:'Financial'},
{t:'AXP',n:'American Express',s:'Financial'},
{t:'C',n:'Citigroup Inc.',s:'Financial'},
{t:'USB',n:'U.S. Bancorp',s:'Financial'},
{t:'PNC',n:'PNC Financial',s:'Financial'},
{t:'COF',n:'Capital One Financial',s:'Financial'},
{t:'PYPL',n:'PayPal Holdings',s:'Financial'},
{t:'SQ',n:'Block Inc.',s:'Financial'},
{t:'SOFI',n:'SoFi Technologies',s:'Financial'},
{t:'BRK.B',n:'Berkshire Hathaway',s:'Financial'},
// ── Energy ────────────────────────────────────
{t:'XOM',n:'Exxon Mobil Corp.',s:'Energy'},
{t:'CVX',n:'Chevron Corp.',s:'Energy'},
{t:'COP',n:'ConocoPhillips',s:'Energy'},
{t:'SLB',n:'Schlumberger Ltd.',s:'Energy'},
{t:'EOG',n:'EOG Resources',s:'Energy'},
{t:'OXY',n:'Occidental Petroleum',s:'Energy'},
{t:'MPC',n:'Marathon Petroleum',s:'Energy'},
{t:'PSX',n:'Phillips 66',s:'Energy'},
{t:'VLO',n:'Valero Energy',s:'Energy'},
{t:'HAL',n:'Halliburton Co.',s:'Energy'},
// ── Industrials ───────────────────────────────
{t:'CAT',n:'Caterpillar Inc.',s:'Industrials'},
{t:'DE',n:'Deere & Co.',s:'Industrials'},
{t:'UNP',n:'Union Pacific Corp.',s:'Industrials'},
{t:'HON',n:'Honeywell International',s:'Industrials'},
{t:'BA',n:'Boeing Co.',s:'Industrials'},
{t:'GE',n:'GE Aerospace',s:'Industrials'},
{t:'LMT',n:'Lockheed Martin',s:'Industrials'},
{t:'RTX',n:'RTX Corp.',s:'Industrials'},
{t:'UPS',n:'United Parcel Service',s:'Industrials'},
{t:'FDX',n:'FedEx Corp.',s:'Industrials'},
{t:'MMM',n:'3M Co.',s:'Industrials'},
{t:'WM',n:'Waste Management',s:'Industrials'},
// ── Utilities ─────────────────────────────────
{t:'NEE',n:'NextEra Energy',s:'Utilities'},
{t:'DUK',n:'Duke Energy',s:'Utilities'},
{t:'SO',n:'Southern Co.',s:'Utilities'},
{t:'D',n:'Dominion Energy',s:'Utilities'},
{t:'AEP',n:'American Electric Power',s:'Utilities'},
{t:'XEL',n:'Xcel Energy',s:'Utilities'},
// ── Real Estate ───────────────────────────────
{t:'AMT',n:'American Tower Corp.',s:'Real Estate'},
{t:'PLD',n:'Prologis Inc.',s:'Real Estate'},
{t:'CCI',n:'Crown Castle International',s:'Real Estate'},
{t:'O',n:'Realty Income Corp.',s:'Real Estate'},
{t:'SPG',n:'Simon Property Group',s:'Real Estate'},
{t:'EQIX',n:'Equinix Inc.',s:'Real Estate'},
// ── Materials ─────────────────────────────────
{t:'LIN',n:'Linde plc',s:'Materials'},
{t:'APD',n:'Air Products & Chemicals',s:'Materials'},
{t:'SHW',n:'Sherwin-Williams',s:'Materials'},
{t:'FCX',n:'Freeport-McMoRan',s:'Materials'},
{t:'NEM',n:'Newmont Corp.',s:'Materials'},
{t:'NUE',n:'Nucor Corp.',s:'Materials'},
{t:'DOW',n:'Dow Inc.',s:'Materials'},
// ── ETFs ──────────────────────────────────────
{t:'VOO',n:'Vanguard S&P 500 ETF',s:'ETF'},
{t:'SPY',n:'SPDR S&P 500 ETF',s:'ETF'},
{t:'QQQ',n:'Invesco Nasdaq-100 ETF',s:'ETF'},
{t:'VTI',n:'Vanguard Total Stock Market',s:'ETF'},
{t:'IWM',n:'iShares Russell 2000',s:'ETF'},
{t:'DIA',n:'SPDR Dow Jones ETF',s:'ETF'},
{t:'VGT',n:'Vanguard Info Tech ETF',s:'ETF'},
{t:'XLK',n:'Technology Select Sector',s:'ETF'},
{t:'XLF',n:'Financial Select Sector',s:'ETF'},
{t:'XLE',n:'Energy Select Sector',s:'ETF'},
{t:'XLV',n:'Health Care Select Sector',s:'ETF'},
{t:'XLY',n:'Consumer Discretionary Sector',s:'ETF'},
{t:'XLP',n:'Consumer Staples Sector',s:'ETF'},
{t:'XLI',n:'Industrial Select Sector',s:'ETF'},
{t:'XLU',n:'Utilities Select Sector',s:'ETF'},
{t:'XLRE',n:'Real Estate Select Sector',s:'ETF'},
{t:'SCHD',n:'Schwab US Dividend Equity',s:'ETF'},
{t:'VYM',n:'Vanguard High Dividend Yield',s:'ETF'},
{t:'ARKK',n:'ARK Innovation ETF',s:'ETF'},
{t:'VIG',n:'Vanguard Dividend Appreciation',s:'ETF'},
{t:'BND',n:'Vanguard Total Bond Market',s:'ETF'},
{t:'GLD',n:'SPDR Gold Shares',s:'ETF'},
{t:'SLV',n:'iShares Silver Trust',s:'ETF'},
{t:'VNQ',n:'Vanguard Real Estate ETF',s:'ETF'},
{t:'VWO',n:'Vanguard Emerging Markets',s:'ETF'},
{t:'EFA',n:'iShares MSCI EAFE',s:'ETF'},
{t:'IBIT',n:'iShares Bitcoin Trust',s:'ETF'},
];

// Quick lookup by ticker
const STOCKS_MAP={};
STOCKS_DB.forEach(s=>{STOCKS_MAP[s.t]=s;});

// Get sector for a ticker
function getSector(ticker){
  const s=STOCKS_MAP[ticker];
  if(s) return s.s;
  // Guess from HUMAN translations (only available on dashboard page)
  if(typeof HUMAN!=='undefined'){
    const h=HUMAN[ticker];
    if(h&&h.sector) return h.sector;
  }
  return 'Other';
}
